version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - twotier-network

  flaskapp:
    build: .
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - twotier-network

volumes:
  mysql-data:

networks:
  twotier-network:
    driver: bridge
